### ISSUE TITLE
Fragment support was dropped with last commit

### ISSUE THREAD

**Issue by goozak** [Ifnot/RestfulizerJs#5]
With the [last commit](https://github.com/Ifnot/RestfulizerJs/commit/1cc9773f05cbac3b7603ebef4774b13d5263b986#diff-503a0236de595036da336044f068d5fb), if the restfulized URL contains a fragment (#), it will remain appended to the last parameter.

For example, the URL `script.php?page=1&val=1#frag` will be converted to a form having `<input type="hidden" value="1#frag" name="val">`.

**Comment by goozak** [comment]
Realized that fragment support was never included.  I must be using a modified version...

**Comment by IfnotFr** [comment]
Hi and thanks for the feeback !

Fragment support is now on the lastest release : https://github.com/Ifnot/RestfulizerJs/commit/46111c572e166fa97f666a6ac099571ac27257d1

:)

**Comment by goozak** [comment]
Wow, that was fast !  :-)

The code I had actually kept the fragment for the action of the form.  Here is the relevant portion of the code I now have, with the support for no parameters from previous commit:

``` javascript
                if (options.parse) {
                    var url = options.target.split('#');
                    var frag = (url.length === 2) ? '#'+url[1] : '';
                    var paramsIndex = url[0].indexOf('?');
                    var hasParams = (paramsIndex > -1);
                    options.target = url[0].substr(0, paramsIndex)+frag;

                    if (hasParams) {
                        var params = url[0].substr(paramsIndex + 1).split('&');
                        for (var i = 0; i < params.length; i++) {
                            var pair = params[i].split('=');
                            inputs += ' <input type="hidden" name="' + decodeURIComponent(pair[0]) + '" value="' + decodeURIComponent(pair[1]) + '">\n';
                        }
                    }
                }
```

**Comment by IfnotFr** [comment]
Thanks for your response.

Hum I understand, my code just drop the fragment. Your code keep the fragment for pushing it to the final url just after the form building ? I am right ?

**Comment by goozak** [comment]
Yes, for example, the URL `script.php?page=1&val=1#frag` will keep the fragment in the `action` attribute:  `<form style="display:none" method="POST" action="script.php#frag">`.
